/**
 * ESPN-specific team name overrides.
 *
 * Maps ESPN displayName/shortName/abbreviation to TrendLine canonical names
 * when the existing team-name-mapping files can't resolve them.
 *
 * Populated incrementally — run a sync, check logs for "Unresolved team" warnings,
 * then add mappings here.
 */

export const espnOverrides: Record<string, Record<string, string>> = {
  NFL: {
    // NFL names match well already; add exceptions here if needed
  },

  NCAAF: {
    // ESPN → TrendLine canonical
    "Hawai'i Rainbow Warriors": "Hawaii",
    "Hawai'i": "Hawaii",
    "HAW": "Hawaii",
    "Miami Hurricanes": "Miami",
    "Miami (OH) RedHawks": "Miami (OH)",
    "UConn Huskies": "Connecticut",
    "UCONN": "Connecticut",
    "UConn": "Connecticut",
    "SMU Mustangs": "SMU",
    "UCF Knights": "UCF",
    "UTSA Roadrunners": "UTSA",
    "UTEP Miners": "UTEP",
    "UAB Blazers": "UAB",
    "UL Monroe Warhawks": "Louisiana-Monroe",
    "ULM": "Louisiana-Monroe",
    "Louisiana Ragin' Cajuns": "Louisiana",
    "ULL": "Louisiana",
    "Appalachian State Mountaineers": "Appalachian State",
    "APP": "Appalachian State",
    "Middle Tennessee Blue Raiders": "Middle Tennessee",
    "MTSU": "Middle Tennessee",
    "FIU Panthers": "FIU",
    "FAU Owls": "FAU",
    "UNLV Rebels": "UNLV",
    "USC Trojans": "USC",
    "LSU Tigers": "LSU",
    "Ole Miss Rebels": "Ole Miss",
    "MISS": "Ole Miss",
  },

  NCAAMB: {
    // ESPN → TrendLine canonical
    "UConn Huskies": "Connecticut",
    "UCONN": "Connecticut",
    "UConn": "Connecticut",
    "Hawai'i Rainbow Warriors": "Hawaii",
    "HAW": "Hawaii",
    "Miami Hurricanes": "Miami",
    "Miami (OH) RedHawks": "Miami (OH)",
    "Saint Joseph's Hawks": "Saint Joseph's",
    "Saint Mary's Gaels": "Saint Mary's",
    "St. John's Red Storm": "St. John's",
    "St. Bonaventure Bonnies": "St. Bonaventure",
    "Loyola Chicago Ramblers": "Loyola Chicago",
    "UNC Tar Heels": "North Carolina",
    "North Carolina Tar Heels": "North Carolina",
    "NC State Wolfpack": "NC State",
    "UL Monroe Warhawks": "Louisiana-Monroe",
    "ULM": "Louisiana-Monroe",
    "Louisiana Ragin' Cajuns": "Louisiana",
    "ULL": "Louisiana",
    "USC Trojans": "USC",
    "LSU Tigers": "LSU",
    "UNLV Rebels": "UNLV",
    "Ole Miss Rebels": "Ole Miss",
    "MISS": "Ole Miss",
    "SMU Mustangs": "SMU",
    "UCF Knights": "UCF",
    "UTSA Roadrunners": "UTSA",
    "UTEP Miners": "UTEP",
    "UAB Blazers": "UAB",
    "FAU Owls": "FAU",
    "FIU Panthers": "FIU",
    "Middle Tennessee Blue Raiders": "Middle Tennessee",
    "MTSU": "Middle Tennessee",
    "Appalachian State Mountaineers": "Appalachian State",
    "APP": "Appalachian State",
    "AR-Pine Bluff": "Arkansas-Pine Bluff",
    "UAPB": "Arkansas-Pine Bluff",
    "Chicago St": "Chicago State",
    "CHST": "Chicago State",
    "Jackson St": "Jackson State",
    "JKST": "Jackson State",
    "UT Rio Grande Valley Vaqueros": "UT Rio Grande Valley",
    "RGV": "UT Rio Grande Valley",
    "East Texas A&M Lions": "East Texas A&M",
    "ETAM": "East Texas A&M",
    "Texas A&M-Corpus Christi Islanders": "Texas A&M-Corpus Christi",
    "AMCC": "Texas A&M-Corpus Christi",
    "Bethune-Cookman Wildcats": "Bethune Cookman",
    "BCU": "Bethune Cookman",
    "Indiana St": "Indiana State",
    "INST": "Indiana State",
    "SE Louisiana": "Southeastern Louisiana",
    "SELA": "Southeastern Louisiana",
    "S Illinois": "Southern Illinois",
    "SIU": "Southern Illinois",
  },
};
