import { Sport, VenueType } from "@prisma/client";

export interface NCAAFTeamSeedData {
  name: string;
  shortName: string;
  slug: string;
  abbreviation: string;
  sport: Sport;
  conference2024: string;
  venue: string;
  venueType: VenueType;
  city: string;
  state: string;
  latitude: number;
  longitude: number;
}

/**
 * All 135 FBS (Football Bowl Subdivision) teams that appeared in NCAA football
 * from 2005-2024. Conference assignments reflect the 2024 season (post-realignment).
 *
 * Slugs match Sports Reference URL format: https://www.sports-reference.com/cfb/schools/{slug}/
 *
 * Note: Idaho dropped to FCS after the 2017 season. Their conference2024 is marked "FCS".
 */
export const ncaafTeams: NCAAFTeamSeedData[] = [
  // ─── SEC (16 teams) ───────────────────────────────
  {
    name: "Alabama Crimson Tide",
    shortName: "Alabama",
    slug: "alabama",
    abbreviation: "ALA",
    sport: Sport.NCAAF,
    conference2024: "SEC",
    venue: "Bryant-Denny Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Tuscaloosa",
    state: "AL",
    latitude: 33.2084,
    longitude: -87.5504,
  },
  {
    name: "Arkansas Razorbacks",
    shortName: "Arkansas",
    slug: "arkansas",
    abbreviation: "ARK",
    sport: Sport.NCAAF,
    conference2024: "SEC",
    venue: "Donald W. Reynolds Razorback Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Fayetteville",
    state: "AR",
    latitude: 36.0685,
    longitude: -94.1793,
  },
  {
    name: "Auburn Tigers",
    shortName: "Auburn",
    slug: "auburn",
    abbreviation: "AUB",
    sport: Sport.NCAAF,
    conference2024: "SEC",
    venue: "Jordan-Hare Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Auburn",
    state: "AL",
    latitude: 32.6025,
    longitude: -85.4899,
  },
  {
    name: "Florida Gators",
    shortName: "Florida",
    slug: "florida",
    abbreviation: "FLA",
    sport: Sport.NCAAF,
    conference2024: "SEC",
    venue: "Ben Hill Griffin Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Gainesville",
    state: "FL",
    latitude: 29.6500,
    longitude: -82.3486,
  },
  {
    name: "Georgia Bulldogs",
    shortName: "Georgia",
    slug: "georgia",
    abbreviation: "UGA",
    sport: Sport.NCAAF,
    conference2024: "SEC",
    venue: "Sanford Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Athens",
    state: "GA",
    latitude: 33.9497,
    longitude: -83.3733,
  },
  {
    name: "Kentucky Wildcats",
    shortName: "Kentucky",
    slug: "kentucky",
    abbreviation: "UK",
    sport: Sport.NCAAF,
    conference2024: "SEC",
    venue: "Kroger Field",
    venueType: VenueType.OUTDOOR,
    city: "Lexington",
    state: "KY",
    latitude: 38.0222,
    longitude: -84.5053,
  },
  {
    name: "LSU Tigers",
    shortName: "LSU",
    slug: "louisiana-state",
    abbreviation: "LSU",
    sport: Sport.NCAAF,
    conference2024: "SEC",
    venue: "Tiger Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Baton Rouge",
    state: "LA",
    latitude: 30.4120,
    longitude: -91.1837,
  },
  {
    name: "Ole Miss Rebels",
    shortName: "Ole Miss",
    slug: "mississippi",
    abbreviation: "MISS",
    sport: Sport.NCAAF,
    conference2024: "SEC",
    venue: "Vaught-Hemingway Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Oxford",
    state: "MS",
    latitude: 34.3618,
    longitude: -89.5344,
  },
  {
    name: "Mississippi State Bulldogs",
    shortName: "Mississippi State",
    slug: "mississippi-state",
    abbreviation: "MSST",
    sport: Sport.NCAAF,
    conference2024: "SEC",
    venue: "Davis Wade Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Starkville",
    state: "MS",
    latitude: 33.4552,
    longitude: -88.7932,
  },
  {
    name: "Missouri Tigers",
    shortName: "Missouri",
    slug: "missouri",
    abbreviation: "MIZ",
    sport: Sport.NCAAF,
    conference2024: "SEC",
    venue: "Faurot Field at Memorial Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Columbia",
    state: "MO",
    latitude: 38.9357,
    longitude: -92.3331,
  },
  {
    name: "Oklahoma Sooners",
    shortName: "Oklahoma",
    slug: "oklahoma",
    abbreviation: "OU",
    sport: Sport.NCAAF,
    conference2024: "SEC",
    venue: "Gaylord Family Oklahoma Memorial Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Norman",
    state: "OK",
    latitude: 35.2058,
    longitude: -97.4425,
  },
  {
    name: "South Carolina Gamecocks",
    shortName: "South Carolina",
    slug: "south-carolina",
    abbreviation: "SC",
    sport: Sport.NCAAF,
    conference2024: "SEC",
    venue: "Williams-Brice Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Columbia",
    state: "SC",
    latitude: 33.9727,
    longitude: -81.0191,
  },
  {
    name: "Tennessee Volunteers",
    shortName: "Tennessee",
    slug: "tennessee",
    abbreviation: "TENN",
    sport: Sport.NCAAF,
    conference2024: "SEC",
    venue: "Neyland Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Knoxville",
    state: "TN",
    latitude: 35.9549,
    longitude: -83.9252,
  },
  {
    name: "Texas Longhorns",
    shortName: "Texas",
    slug: "texas",
    abbreviation: "TEX",
    sport: Sport.NCAAF,
    conference2024: "SEC",
    venue: "Darrell K Royal-Texas Memorial Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Austin",
    state: "TX",
    latitude: 30.2836,
    longitude: -97.7325,
  },
  {
    name: "Texas A&M Aggies",
    shortName: "Texas A&M",
    slug: "texas-am",
    abbreviation: "TAMU",
    sport: Sport.NCAAF,
    conference2024: "SEC",
    venue: "Kyle Field",
    venueType: VenueType.OUTDOOR,
    city: "College Station",
    state: "TX",
    latitude: 30.6102,
    longitude: -96.3404,
  },
  {
    name: "Vanderbilt Commodores",
    shortName: "Vanderbilt",
    slug: "vanderbilt",
    abbreviation: "VAN",
    sport: Sport.NCAAF,
    conference2024: "SEC",
    venue: "FirstBank Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Nashville",
    state: "TN",
    latitude: 36.1440,
    longitude: -86.8090,
  },

  // ─── BIG TEN (18 teams) ──────────────────────────
  {
    name: "Illinois Fighting Illini",
    shortName: "Illinois",
    slug: "illinois",
    abbreviation: "ILL",
    sport: Sport.NCAAF,
    conference2024: "Big Ten",
    venue: "Memorial Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Champaign",
    state: "IL",
    latitude: 40.0992,
    longitude: -88.2360,
  },
  {
    name: "Indiana Hoosiers",
    shortName: "Indiana",
    slug: "indiana",
    abbreviation: "IND",
    sport: Sport.NCAAF,
    conference2024: "Big Ten",
    venue: "Memorial Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Bloomington",
    state: "IN",
    latitude: 39.1808,
    longitude: -86.5257,
  },
  {
    name: "Iowa Hawkeyes",
    shortName: "Iowa",
    slug: "iowa",
    abbreviation: "IOWA",
    sport: Sport.NCAAF,
    conference2024: "Big Ten",
    venue: "Kinnick Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Iowa City",
    state: "IA",
    latitude: 41.6589,
    longitude: -91.5510,
  },
  {
    name: "Maryland Terrapins",
    shortName: "Maryland",
    slug: "maryland",
    abbreviation: "MD",
    sport: Sport.NCAAF,
    conference2024: "Big Ten",
    venue: "SECU Stadium",
    venueType: VenueType.OUTDOOR,
    city: "College Park",
    state: "MD",
    latitude: 38.9908,
    longitude: -76.9488,
  },
  {
    name: "Michigan Wolverines",
    shortName: "Michigan",
    slug: "michigan",
    abbreviation: "MICH",
    sport: Sport.NCAAF,
    conference2024: "Big Ten",
    venue: "Michigan Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Ann Arbor",
    state: "MI",
    latitude: 42.2658,
    longitude: -83.7486,
  },
  {
    name: "Michigan State Spartans",
    shortName: "Michigan State",
    slug: "michigan-state",
    abbreviation: "MSU",
    sport: Sport.NCAAF,
    conference2024: "Big Ten",
    venue: "Spartan Stadium",
    venueType: VenueType.OUTDOOR,
    city: "East Lansing",
    state: "MI",
    latitude: 42.7282,
    longitude: -84.4831,
  },
  {
    name: "Minnesota Golden Gophers",
    shortName: "Minnesota",
    slug: "minnesota",
    abbreviation: "MINN",
    sport: Sport.NCAAF,
    conference2024: "Big Ten",
    venue: "Huntington Bank Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Minneapolis",
    state: "MN",
    latitude: 44.9764,
    longitude: -93.2248,
  },
  {
    name: "Nebraska Cornhuskers",
    shortName: "Nebraska",
    slug: "nebraska",
    abbreviation: "NEB",
    sport: Sport.NCAAF,
    conference2024: "Big Ten",
    venue: "Memorial Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Lincoln",
    state: "NE",
    latitude: 40.8205,
    longitude: -96.7055,
  },
  {
    name: "Northwestern Wildcats",
    shortName: "Northwestern",
    slug: "northwestern",
    abbreviation: "NW",
    sport: Sport.NCAAF,
    conference2024: "Big Ten",
    venue: "Martin Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Evanston",
    state: "IL",
    latitude: 42.0652,
    longitude: -87.6743,
  },
  {
    name: "Ohio State Buckeyes",
    shortName: "Ohio State",
    slug: "ohio-state",
    abbreviation: "OSU",
    sport: Sport.NCAAF,
    conference2024: "Big Ten",
    venue: "Ohio Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Columbus",
    state: "OH",
    latitude: 40.0017,
    longitude: -83.0195,
  },
  {
    name: "Oregon Ducks",
    shortName: "Oregon",
    slug: "oregon",
    abbreviation: "ORE",
    sport: Sport.NCAAF,
    conference2024: "Big Ten",
    venue: "Autzen Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Eugene",
    state: "OR",
    latitude: 44.0584,
    longitude: -123.0680,
  },
  {
    name: "Penn State Nittany Lions",
    shortName: "Penn State",
    slug: "penn-state",
    abbreviation: "PSU",
    sport: Sport.NCAAF,
    conference2024: "Big Ten",
    venue: "Beaver Stadium",
    venueType: VenueType.OUTDOOR,
    city: "University Park",
    state: "PA",
    latitude: 40.8122,
    longitude: -77.8561,
  },
  {
    name: "Purdue Boilermakers",
    shortName: "Purdue",
    slug: "purdue",
    abbreviation: "PUR",
    sport: Sport.NCAAF,
    conference2024: "Big Ten",
    venue: "Ross-Ade Stadium",
    venueType: VenueType.OUTDOOR,
    city: "West Lafayette",
    state: "IN",
    latitude: 40.4340,
    longitude: -86.9189,
  },
  {
    name: "Rutgers Scarlet Knights",
    shortName: "Rutgers",
    slug: "rutgers",
    abbreviation: "RUT",
    sport: Sport.NCAAF,
    conference2024: "Big Ten",
    venue: "SHI Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Piscataway",
    state: "NJ",
    latitude: 40.5139,
    longitude: -74.4653,
  },
  {
    name: "UCLA Bruins",
    shortName: "UCLA",
    slug: "ucla",
    abbreviation: "UCLA",
    sport: Sport.NCAAF,
    conference2024: "Big Ten",
    venue: "Rose Bowl",
    venueType: VenueType.OUTDOOR,
    city: "Pasadena",
    state: "CA",
    latitude: 34.1613,
    longitude: -118.1676,
  },
  {
    name: "USC Trojans",
    shortName: "USC",
    slug: "southern-california",
    abbreviation: "USC",
    sport: Sport.NCAAF,
    conference2024: "Big Ten",
    venue: "Los Angeles Memorial Coliseum",
    venueType: VenueType.OUTDOOR,
    city: "Los Angeles",
    state: "CA",
    latitude: 34.0141,
    longitude: -118.2879,
  },
  {
    name: "Washington Huskies",
    shortName: "Washington",
    slug: "washington",
    abbreviation: "WASH",
    sport: Sport.NCAAF,
    conference2024: "Big Ten",
    venue: "Husky Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Seattle",
    state: "WA",
    latitude: 47.6505,
    longitude: -122.3017,
  },
  {
    name: "Wisconsin Badgers",
    shortName: "Wisconsin",
    slug: "wisconsin",
    abbreviation: "WIS",
    sport: Sport.NCAAF,
    conference2024: "Big Ten",
    venue: "Camp Randall Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Madison",
    state: "WI",
    latitude: 43.0700,
    longitude: -89.4128,
  },

  // ─── BIG 12 (16 teams) ───────────────────────────
  {
    name: "Arizona Wildcats",
    shortName: "Arizona",
    slug: "arizona",
    abbreviation: "ARIZ",
    sport: Sport.NCAAF,
    conference2024: "Big 12",
    venue: "Arizona Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Tucson",
    state: "AZ",
    latitude: 32.2286,
    longitude: -110.9489,
  },
  {
    name: "Arizona State Sun Devils",
    shortName: "Arizona State",
    slug: "arizona-state",
    abbreviation: "ASU",
    sport: Sport.NCAAF,
    conference2024: "Big 12",
    venue: "Mountain America Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Tempe",
    state: "AZ",
    latitude: 33.4264,
    longitude: -111.9325,
  },
  {
    name: "Baylor Bears",
    shortName: "Baylor",
    slug: "baylor",
    abbreviation: "BAY",
    sport: Sport.NCAAF,
    conference2024: "Big 12",
    venue: "McLane Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Waco",
    state: "TX",
    latitude: 31.5586,
    longitude: -97.1150,
  },
  {
    name: "BYU Cougars",
    shortName: "BYU",
    slug: "brigham-young",
    abbreviation: "BYU",
    sport: Sport.NCAAF,
    conference2024: "Big 12",
    venue: "LaVell Edwards Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Provo",
    state: "UT",
    latitude: 40.2573,
    longitude: -111.6546,
  },
  {
    name: "UCF Knights",
    shortName: "UCF",
    slug: "central-florida",
    abbreviation: "UCF",
    sport: Sport.NCAAF,
    conference2024: "Big 12",
    venue: "FBC Mortgage Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Orlando",
    state: "FL",
    latitude: 28.6078,
    longitude: -81.1919,
  },
  {
    name: "Cincinnati Bearcats",
    shortName: "Cincinnati",
    slug: "cincinnati",
    abbreviation: "CIN",
    sport: Sport.NCAAF,
    conference2024: "Big 12",
    venue: "Nippert Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Cincinnati",
    state: "OH",
    latitude: 39.1311,
    longitude: -84.5167,
  },
  {
    name: "Colorado Buffaloes",
    shortName: "Colorado",
    slug: "colorado",
    abbreviation: "COL",
    sport: Sport.NCAAF,
    conference2024: "Big 12",
    venue: "Folsom Field",
    venueType: VenueType.OUTDOOR,
    city: "Boulder",
    state: "CO",
    latitude: 40.0094,
    longitude: -105.2668,
  },
  {
    name: "Houston Cougars",
    shortName: "Houston",
    slug: "houston",
    abbreviation: "HOU",
    sport: Sport.NCAAF,
    conference2024: "Big 12",
    venue: "TDECU Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Houston",
    state: "TX",
    latitude: 29.7220,
    longitude: -95.3502,
  },
  {
    name: "Iowa State Cyclones",
    shortName: "Iowa State",
    slug: "iowa-state",
    abbreviation: "ISU",
    sport: Sport.NCAAF,
    conference2024: "Big 12",
    venue: "Jack Trice Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Ames",
    state: "IA",
    latitude: 42.0140,
    longitude: -93.6358,
  },
  {
    name: "Kansas Jayhawks",
    shortName: "Kansas",
    slug: "kansas",
    abbreviation: "KU",
    sport: Sport.NCAAF,
    conference2024: "Big 12",
    venue: "David Booth Kansas Memorial Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Lawrence",
    state: "KS",
    latitude: 38.9583,
    longitude: -95.2525,
  },
  {
    name: "Kansas State Wildcats",
    shortName: "Kansas State",
    slug: "kansas-state",
    abbreviation: "KSU",
    sport: Sport.NCAAF,
    conference2024: "Big 12",
    venue: "Bill Snyder Family Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Manhattan",
    state: "KS",
    latitude: 39.2019,
    longitude: -96.5926,
  },
  {
    name: "Oklahoma State Cowboys",
    shortName: "Oklahoma State",
    slug: "oklahoma-state",
    abbreviation: "OKST",
    sport: Sport.NCAAF,
    conference2024: "Big 12",
    venue: "Boone Pickens Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Stillwater",
    state: "OK",
    latitude: 36.1261,
    longitude: -97.0666,
  },
  {
    name: "TCU Horned Frogs",
    shortName: "TCU",
    slug: "texas-christian",
    abbreviation: "TCU",
    sport: Sport.NCAAF,
    conference2024: "Big 12",
    venue: "Amon G. Carter Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Fort Worth",
    state: "TX",
    latitude: 32.7098,
    longitude: -97.3685,
  },
  {
    name: "Texas Tech Red Raiders",
    shortName: "Texas Tech",
    slug: "texas-tech",
    abbreviation: "TTU",
    sport: Sport.NCAAF,
    conference2024: "Big 12",
    venue: "Jones AT&T Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Lubbock",
    state: "TX",
    latitude: 33.5908,
    longitude: -101.8726,
  },
  {
    name: "Utah Utes",
    shortName: "Utah",
    slug: "utah",
    abbreviation: "UTAH",
    sport: Sport.NCAAF,
    conference2024: "Big 12",
    venue: "Rice-Eccles Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Salt Lake City",
    state: "UT",
    latitude: 40.7600,
    longitude: -111.8486,
  },
  {
    name: "West Virginia Mountaineers",
    shortName: "West Virginia",
    slug: "west-virginia",
    abbreviation: "WVU",
    sport: Sport.NCAAF,
    conference2024: "Big 12",
    venue: "Mountaineer Field at Milan Puskar Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Morgantown",
    state: "WV",
    latitude: 39.6500,
    longitude: -79.9540,
  },

  // ─── ACC (17 teams) ──────────────────────────────
  {
    name: "Boston College Eagles",
    shortName: "Boston College",
    slug: "boston-college",
    abbreviation: "BC",
    sport: Sport.NCAAF,
    conference2024: "ACC",
    venue: "Alumni Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Chestnut Hill",
    state: "MA",
    latitude: 42.3355,
    longitude: -71.1685,
  },
  {
    name: "California Golden Bears",
    shortName: "California",
    slug: "california",
    abbreviation: "CAL",
    sport: Sport.NCAAF,
    conference2024: "ACC",
    venue: "California Memorial Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Berkeley",
    state: "CA",
    latitude: 37.8709,
    longitude: -122.2506,
  },
  {
    name: "Clemson Tigers",
    shortName: "Clemson",
    slug: "clemson",
    abbreviation: "CLEM",
    sport: Sport.NCAAF,
    conference2024: "ACC",
    venue: "Memorial Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Clemson",
    state: "SC",
    latitude: 34.6784,
    longitude: -82.8432,
  },
  {
    name: "Duke Blue Devils",
    shortName: "Duke",
    slug: "duke",
    abbreviation: "DUKE",
    sport: Sport.NCAAF,
    conference2024: "ACC",
    venue: "Wallace Wade Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Durham",
    state: "NC",
    latitude: 36.0019,
    longitude: -78.9426,
  },
  {
    name: "Florida State Seminoles",
    shortName: "Florida State",
    slug: "florida-state",
    abbreviation: "FSU",
    sport: Sport.NCAAF,
    conference2024: "ACC",
    venue: "Doak Campbell Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Tallahassee",
    state: "FL",
    latitude: 30.4383,
    longitude: -84.3041,
  },
  {
    name: "Georgia Tech Yellow Jackets",
    shortName: "Georgia Tech",
    slug: "georgia-tech",
    abbreviation: "GT",
    sport: Sport.NCAAF,
    conference2024: "ACC",
    venue: "Bobby Dodd Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Atlanta",
    state: "GA",
    latitude: 33.7724,
    longitude: -84.3927,
  },
  {
    name: "Louisville Cardinals",
    shortName: "Louisville",
    slug: "louisville",
    abbreviation: "LOU",
    sport: Sport.NCAAF,
    conference2024: "ACC",
    venue: "L&N Federal Credit Union Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Louisville",
    state: "KY",
    latitude: 38.2130,
    longitude: -85.7587,
  },
  {
    name: "Miami Hurricanes",
    shortName: "Miami",
    slug: "miami-fl",
    abbreviation: "MIA",
    sport: Sport.NCAAF,
    conference2024: "ACC",
    venue: "Hard Rock Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Miami Gardens",
    state: "FL",
    latitude: 25.9580,
    longitude: -80.2389,
  },
  {
    name: "North Carolina Tar Heels",
    shortName: "North Carolina",
    slug: "north-carolina",
    abbreviation: "UNC",
    sport: Sport.NCAAF,
    conference2024: "ACC",
    venue: "Kenan Memorial Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Chapel Hill",
    state: "NC",
    latitude: 35.9050,
    longitude: -79.0476,
  },
  {
    name: "NC State Wolfpack",
    shortName: "NC State",
    slug: "north-carolina-state",
    abbreviation: "NCST",
    sport: Sport.NCAAF,
    conference2024: "ACC",
    venue: "Carter-Finley Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Raleigh",
    state: "NC",
    latitude: 35.8032,
    longitude: -78.7117,
  },
  {
    name: "Pittsburgh Panthers",
    shortName: "Pittsburgh",
    slug: "pittsburgh",
    abbreviation: "PITT",
    sport: Sport.NCAAF,
    conference2024: "ACC",
    venue: "Acrisure Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Pittsburgh",
    state: "PA",
    latitude: 40.4468,
    longitude: -80.0158,
  },
  {
    name: "SMU Mustangs",
    shortName: "SMU",
    slug: "southern-methodist",
    abbreviation: "SMU",
    sport: Sport.NCAAF,
    conference2024: "ACC",
    venue: "Gerald J. Ford Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Dallas",
    state: "TX",
    latitude: 32.8365,
    longitude: -96.7833,
  },
  {
    name: "Stanford Cardinal",
    shortName: "Stanford",
    slug: "stanford",
    abbreviation: "STAN",
    sport: Sport.NCAAF,
    conference2024: "ACC",
    venue: "Stanford Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Stanford",
    state: "CA",
    latitude: 37.4346,
    longitude: -122.1609,
  },
  {
    name: "Syracuse Orange",
    shortName: "Syracuse",
    slug: "syracuse",
    abbreviation: "SYR",
    sport: Sport.NCAAF,
    conference2024: "ACC",
    venue: "JMA Wireless Dome",
    venueType: VenueType.DOME,
    city: "Syracuse",
    state: "NY",
    latitude: 43.0362,
    longitude: -76.1363,
  },
  {
    name: "Virginia Cavaliers",
    shortName: "Virginia",
    slug: "virginia",
    abbreviation: "UVA",
    sport: Sport.NCAAF,
    conference2024: "ACC",
    venue: "Scott Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Charlottesville",
    state: "VA",
    latitude: 38.0312,
    longitude: -78.5133,
  },
  {
    name: "Virginia Tech Hokies",
    shortName: "Virginia Tech",
    slug: "virginia-tech",
    abbreviation: "VT",
    sport: Sport.NCAAF,
    conference2024: "ACC",
    venue: "Lane Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Blacksburg",
    state: "VA",
    latitude: 37.2200,
    longitude: -80.4180,
  },
  {
    name: "Wake Forest Demon Deacons",
    shortName: "Wake Forest",
    slug: "wake-forest",
    abbreviation: "WAKE",
    sport: Sport.NCAAF,
    conference2024: "ACC",
    venue: "Allegacy Federal Credit Union Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Winston-Salem",
    state: "NC",
    latitude: 36.1345,
    longitude: -80.2575,
  },

  // ─── PAC-12 (2 remaining teams) ──────────────────
  {
    name: "Oregon State Beavers",
    shortName: "Oregon State",
    slug: "oregon-state",
    abbreviation: "ORST",
    sport: Sport.NCAAF,
    conference2024: "Pac-12",
    venue: "Reser Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Corvallis",
    state: "OR",
    latitude: 44.5594,
    longitude: -123.2816,
  },
  {
    name: "Washington State Cougars",
    shortName: "Washington State",
    slug: "washington-state",
    abbreviation: "WSU",
    sport: Sport.NCAAF,
    conference2024: "Pac-12",
    venue: "Gesa Field at Martin Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Pullman",
    state: "WA",
    latitude: 46.7325,
    longitude: -117.1581,
  },

  // ─── INDEPENDENTS ─────────────────────────────────
  {
    name: "Notre Dame Fighting Irish",
    shortName: "Notre Dame",
    slug: "notre-dame",
    abbreviation: "ND",
    sport: Sport.NCAAF,
    conference2024: "Independent",
    venue: "Notre Dame Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Notre Dame",
    state: "IN",
    latitude: 41.6983,
    longitude: -86.2340,
  },
  {
    name: "UConn Huskies",
    shortName: "Connecticut",
    slug: "connecticut",
    abbreviation: "CONN",
    sport: Sport.NCAAF,
    conference2024: "Independent",
    venue: "Rentschler Field at Pratt & Whitney Stadium",
    venueType: VenueType.OUTDOOR,
    city: "East Hartford",
    state: "CT",
    latitude: 41.7628,
    longitude: -72.6120,
  },
  {
    name: "UMass Minutemen",
    shortName: "Massachusetts",
    slug: "massachusetts",
    abbreviation: "UMASS",
    sport: Sport.NCAAF,
    conference2024: "Independent",
    venue: "Warren McGuirk Alumni Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Amherst",
    state: "MA",
    latitude: 42.3862,
    longitude: -72.5354,
  },

  // ─── AAC (14 teams) ──────────────────────────────
  {
    name: "Army Black Knights",
    shortName: "Army",
    slug: "army",
    abbreviation: "ARMY",
    sport: Sport.NCAAF,
    conference2024: "AAC",
    venue: "Michie Stadium",
    venueType: VenueType.OUTDOOR,
    city: "West Point",
    state: "NY",
    latitude: 41.3884,
    longitude: -73.9649,
  },
  {
    name: "Charlotte 49ers",
    shortName: "Charlotte",
    slug: "charlotte",
    abbreviation: "CLT",
    sport: Sport.NCAAF,
    conference2024: "AAC",
    venue: "Jerry Richardson Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Charlotte",
    state: "NC",
    latitude: 35.3087,
    longitude: -80.7336,
  },
  {
    name: "East Carolina Pirates",
    shortName: "East Carolina",
    slug: "east-carolina",
    abbreviation: "ECU",
    sport: Sport.NCAAF,
    conference2024: "AAC",
    venue: "Dowdy-Ficklen Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Greenville",
    state: "NC",
    latitude: 35.6041,
    longitude: -77.3635,
  },
  {
    name: "FAU Owls",
    shortName: "Florida Atlantic",
    slug: "florida-atlantic",
    abbreviation: "FAU",
    sport: Sport.NCAAF,
    conference2024: "AAC",
    venue: "FAU Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Boca Raton",
    state: "FL",
    latitude: 26.3727,
    longitude: -80.1018,
  },
  {
    name: "Memphis Tigers",
    shortName: "Memphis",
    slug: "memphis",
    abbreviation: "MEM",
    sport: Sport.NCAAF,
    conference2024: "AAC",
    venue: "Simmons Bank Liberty Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Memphis",
    state: "TN",
    latitude: 35.1203,
    longitude: -89.9982,
  },
  {
    name: "Navy Midshipmen",
    shortName: "Navy",
    slug: "navy",
    abbreviation: "NAVY",
    sport: Sport.NCAAF,
    conference2024: "AAC",
    venue: "Navy-Marine Corps Memorial Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Annapolis",
    state: "MD",
    latitude: 38.9840,
    longitude: -76.4871,
  },
  {
    name: "North Texas Mean Green",
    shortName: "North Texas",
    slug: "north-texas",
    abbreviation: "UNT",
    sport: Sport.NCAAF,
    conference2024: "AAC",
    venue: "Apogee Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Denton",
    state: "TX",
    latitude: 33.2235,
    longitude: -97.1520,
  },
  {
    name: "Rice Owls",
    shortName: "Rice",
    slug: "rice",
    abbreviation: "RICE",
    sport: Sport.NCAAF,
    conference2024: "AAC",
    venue: "Rice Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Houston",
    state: "TX",
    latitude: 29.7163,
    longitude: -95.4097,
  },
  {
    name: "South Florida Bulls",
    shortName: "South Florida",
    slug: "south-florida",
    abbreviation: "USF",
    sport: Sport.NCAAF,
    conference2024: "AAC",
    venue: "Raymond James Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Tampa",
    state: "FL",
    latitude: 27.9759,
    longitude: -82.5033,
  },
  {
    name: "Temple Owls",
    shortName: "Temple",
    slug: "temple",
    abbreviation: "TEM",
    sport: Sport.NCAAF,
    conference2024: "AAC",
    venue: "Lincoln Financial Field",
    venueType: VenueType.OUTDOOR,
    city: "Philadelphia",
    state: "PA",
    latitude: 39.9008,
    longitude: -75.1675,
  },
  {
    name: "Tulane Green Wave",
    shortName: "Tulane",
    slug: "tulane",
    abbreviation: "TUL",
    sport: Sport.NCAAF,
    conference2024: "AAC",
    venue: "Yulman Stadium",
    venueType: VenueType.OUTDOOR,
    city: "New Orleans",
    state: "LA",
    latitude: 29.9461,
    longitude: -90.1198,
  },
  {
    name: "Tulsa Golden Hurricane",
    shortName: "Tulsa",
    slug: "tulsa",
    abbreviation: "TLSA",
    sport: Sport.NCAAF,
    conference2024: "AAC",
    venue: "H.A. Chapman Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Tulsa",
    state: "OK",
    latitude: 36.1490,
    longitude: -95.9466,
  },
  {
    name: "UTSA Roadrunners",
    shortName: "UTSA",
    slug: "texas-san-antonio",
    abbreviation: "UTSA",
    sport: Sport.NCAAF,
    conference2024: "AAC",
    venue: "Alamodome",
    venueType: VenueType.DOME,
    city: "San Antonio",
    state: "TX",
    latitude: 29.4168,
    longitude: -98.4782,
  },

  // ─── SUN BELT (14 teams) ─────────────────────────
  {
    name: "Appalachian State Mountaineers",
    shortName: "Appalachian State",
    slug: "appalachian-state",
    abbreviation: "APP",
    sport: Sport.NCAAF,
    conference2024: "Sun Belt",
    venue: "Kidd Brewer Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Boone",
    state: "NC",
    latitude: 36.2131,
    longitude: -81.6853,
  },
  {
    name: "Arkansas State Red Wolves",
    shortName: "Arkansas State",
    slug: "arkansas-state",
    abbreviation: "ARST",
    sport: Sport.NCAAF,
    conference2024: "Sun Belt",
    venue: "Centennial Bank Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Jonesboro",
    state: "AR",
    latitude: 35.8462,
    longitude: -90.6835,
  },
  {
    name: "Coastal Carolina Chanticleers",
    shortName: "Coastal Carolina",
    slug: "coastal-carolina",
    abbreviation: "CCU",
    sport: Sport.NCAAF,
    conference2024: "Sun Belt",
    venue: "Brooks Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Conway",
    state: "SC",
    latitude: 33.7968,
    longitude: -79.0154,
  },
  {
    name: "Georgia Southern Eagles",
    shortName: "Georgia Southern",
    slug: "georgia-southern",
    abbreviation: "GASO",
    sport: Sport.NCAAF,
    conference2024: "Sun Belt",
    venue: "Allen E. Paulson Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Statesboro",
    state: "GA",
    latitude: 32.4228,
    longitude: -81.7828,
  },
  {
    name: "Georgia State Panthers",
    shortName: "Georgia State",
    slug: "georgia-state",
    abbreviation: "GAST",
    sport: Sport.NCAAF,
    conference2024: "Sun Belt",
    venue: "Center Parc Credit Union Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Atlanta",
    state: "GA",
    latitude: 33.7407,
    longitude: -84.3915,
  },
  {
    name: "James Madison Dukes",
    shortName: "James Madison",
    slug: "james-madison",
    abbreviation: "JMU",
    sport: Sport.NCAAF,
    conference2024: "Sun Belt",
    venue: "Bridgeforth Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Harrisonburg",
    state: "VA",
    latitude: 38.4355,
    longitude: -78.8721,
  },
  {
    name: "Louisiana Ragin' Cajuns",
    shortName: "Louisiana",
    slug: "louisiana-lafayette",
    abbreviation: "ULL",
    sport: Sport.NCAAF,
    conference2024: "Sun Belt",
    venue: "Cajun Field",
    venueType: VenueType.OUTDOOR,
    city: "Lafayette",
    state: "LA",
    latitude: 30.2141,
    longitude: -92.0186,
  },
  {
    name: "Louisiana-Monroe Warhawks",
    shortName: "Louisiana-Monroe",
    slug: "louisiana-monroe",
    abbreviation: "ULM",
    sport: Sport.NCAAF,
    conference2024: "Sun Belt",
    venue: "Malone Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Monroe",
    state: "LA",
    latitude: 32.5283,
    longitude: -92.0752,
  },
  {
    name: "Marshall Thundering Herd",
    shortName: "Marshall",
    slug: "marshall",
    abbreviation: "MRSH",
    sport: Sport.NCAAF,
    conference2024: "Sun Belt",
    venue: "Joan C. Edwards Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Huntington",
    state: "WV",
    latitude: 38.4226,
    longitude: -82.4265,
  },
  {
    name: "Old Dominion Monarchs",
    shortName: "Old Dominion",
    slug: "old-dominion",
    abbreviation: "ODU",
    sport: Sport.NCAAF,
    conference2024: "Sun Belt",
    venue: "S.B. Ballard Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Norfolk",
    state: "VA",
    latitude: 36.8850,
    longitude: -76.3040,
  },
  {
    name: "South Alabama Jaguars",
    shortName: "South Alabama",
    slug: "south-alabama",
    abbreviation: "USA",
    sport: Sport.NCAAF,
    conference2024: "Sun Belt",
    venue: "Hancock Whitney Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Mobile",
    state: "AL",
    latitude: 30.6968,
    longitude: -88.1785,
  },
  {
    name: "Southern Miss Golden Eagles",
    shortName: "Southern Mississippi",
    slug: "southern-mississippi",
    abbreviation: "USM",
    sport: Sport.NCAAF,
    conference2024: "Sun Belt",
    venue: "M.M. Roberts Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Hattiesburg",
    state: "MS",
    latitude: 31.3273,
    longitude: -89.3353,
  },
  {
    name: "Texas State Bobcats",
    shortName: "Texas State",
    slug: "texas-state",
    abbreviation: "TXST",
    sport: Sport.NCAAF,
    conference2024: "Sun Belt",
    venue: "UFCU Stadium",
    venueType: VenueType.OUTDOOR,
    city: "San Marcos",
    state: "TX",
    latitude: 29.8903,
    longitude: -97.9301,
  },
  {
    name: "Troy Trojans",
    shortName: "Troy",
    slug: "troy",
    abbreviation: "TROY",
    sport: Sport.NCAAF,
    conference2024: "Sun Belt",
    venue: "Veterans Memorial Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Troy",
    state: "AL",
    latitude: 31.7942,
    longitude: -85.9658,
  },

  // ─── MOUNTAIN WEST (12 teams) ────────────────────
  {
    name: "Air Force Falcons",
    shortName: "Air Force",
    slug: "air-force",
    abbreviation: "AF",
    sport: Sport.NCAAF,
    conference2024: "Mountain West",
    venue: "Falcon Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Colorado Springs",
    state: "CO",
    latitude: 38.9980,
    longitude: -104.8438,
  },
  {
    name: "Boise State Broncos",
    shortName: "Boise State",
    slug: "boise-state",
    abbreviation: "BSU",
    sport: Sport.NCAAF,
    conference2024: "Mountain West",
    venue: "Albertsons Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Boise",
    state: "ID",
    latitude: 43.6028,
    longitude: -116.1975,
  },
  {
    name: "Colorado State Rams",
    shortName: "Colorado State",
    slug: "colorado-state",
    abbreviation: "CSU",
    sport: Sport.NCAAF,
    conference2024: "Mountain West",
    venue: "Canvas Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Fort Collins",
    state: "CO",
    latitude: 40.5764,
    longitude: -105.0849,
  },
  {
    name: "Fresno State Bulldogs",
    shortName: "Fresno State",
    slug: "fresno-state",
    abbreviation: "FRES",
    sport: Sport.NCAAF,
    conference2024: "Mountain West",
    venue: "Valley Children's Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Fresno",
    state: "CA",
    latitude: 36.8128,
    longitude: -119.7283,
  },
  {
    name: "Hawaii Rainbow Warriors",
    shortName: "Hawaii",
    slug: "hawaii",
    abbreviation: "HAW",
    sport: Sport.NCAAF,
    conference2024: "Mountain West",
    venue: "Clarence T.C. Ching Athletics Complex",
    venueType: VenueType.OUTDOOR,
    city: "Honolulu",
    state: "HI",
    latitude: 21.2969,
    longitude: -157.8171,
  },
  {
    name: "Nevada Wolf Pack",
    shortName: "Nevada",
    slug: "nevada",
    abbreviation: "NEV",
    sport: Sport.NCAAF,
    conference2024: "Mountain West",
    venue: "Mackay Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Reno",
    state: "NV",
    latitude: 39.5472,
    longitude: -119.8163,
  },
  {
    name: "UNLV Rebels",
    shortName: "UNLV",
    slug: "nevada-las-vegas",
    abbreviation: "UNLV",
    sport: Sport.NCAAF,
    conference2024: "Mountain West",
    venue: "Allegiant Stadium",
    venueType: VenueType.DOME,
    city: "Las Vegas",
    state: "NV",
    latitude: 36.0908,
    longitude: -115.1833,
  },
  {
    name: "New Mexico Lobos",
    shortName: "New Mexico",
    slug: "new-mexico",
    abbreviation: "UNM",
    sport: Sport.NCAAF,
    conference2024: "Mountain West",
    venue: "University Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Albuquerque",
    state: "NM",
    latitude: 35.0775,
    longitude: -106.6245,
  },
  {
    name: "San Diego State Aztecs",
    shortName: "San Diego State",
    slug: "san-diego-state",
    abbreviation: "SDSU",
    sport: Sport.NCAAF,
    conference2024: "Mountain West",
    venue: "Snapdragon Stadium",
    venueType: VenueType.OUTDOOR,
    city: "San Diego",
    state: "CA",
    latitude: 32.7833,
    longitude: -117.1194,
  },
  {
    name: "San Jose State Spartans",
    shortName: "San Jose State",
    slug: "san-jose-state",
    abbreviation: "SJSU",
    sport: Sport.NCAAF,
    conference2024: "Mountain West",
    venue: "CEFCU Stadium",
    venueType: VenueType.OUTDOOR,
    city: "San Jose",
    state: "CA",
    latitude: 37.3203,
    longitude: -121.8677,
  },
  {
    name: "Utah State Aggies",
    shortName: "Utah State",
    slug: "utah-state",
    abbreviation: "USU",
    sport: Sport.NCAAF,
    conference2024: "Mountain West",
    venue: "Maverik Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Logan",
    state: "UT",
    latitude: 41.7519,
    longitude: -111.8113,
  },
  {
    name: "Wyoming Cowboys",
    shortName: "Wyoming",
    slug: "wyoming",
    abbreviation: "WYO",
    sport: Sport.NCAAF,
    conference2024: "Mountain West",
    venue: "War Memorial Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Laramie",
    state: "WY",
    latitude: 41.3155,
    longitude: -105.5676,
  },

  // ─── MAC (12 teams) ──────────────────────────────
  {
    name: "Akron Zips",
    shortName: "Akron",
    slug: "akron",
    abbreviation: "AKR",
    sport: Sport.NCAAF,
    conference2024: "MAC",
    venue: "InfoCision Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Akron",
    state: "OH",
    latitude: 41.0758,
    longitude: -81.5085,
  },
  {
    name: "Ball State Cardinals",
    shortName: "Ball State",
    slug: "ball-state",
    abbreviation: "BALL",
    sport: Sport.NCAAF,
    conference2024: "MAC",
    venue: "Scheumann Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Muncie",
    state: "IN",
    latitude: 40.2073,
    longitude: -85.4037,
  },
  {
    name: "Bowling Green Falcons",
    shortName: "Bowling Green State",
    slug: "bowling-green-state",
    abbreviation: "BGSU",
    sport: Sport.NCAAF,
    conference2024: "MAC",
    venue: "Doyt Perry Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Bowling Green",
    state: "OH",
    latitude: 41.3787,
    longitude: -83.6277,
  },
  {
    name: "Buffalo Bulls",
    shortName: "Buffalo",
    slug: "buffalo",
    abbreviation: "BUFF",
    sport: Sport.NCAAF,
    conference2024: "MAC",
    venue: "UB Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Amherst",
    state: "NY",
    latitude: 43.0006,
    longitude: -78.7770,
  },
  {
    name: "Central Michigan Chippewas",
    shortName: "Central Michigan",
    slug: "central-michigan",
    abbreviation: "CMU",
    sport: Sport.NCAAF,
    conference2024: "MAC",
    venue: "Kelly/Shorts Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Mount Pleasant",
    state: "MI",
    latitude: 43.5861,
    longitude: -84.7677,
  },
  {
    name: "Eastern Michigan Eagles",
    shortName: "Eastern Michigan",
    slug: "eastern-michigan",
    abbreviation: "EMU",
    sport: Sport.NCAAF,
    conference2024: "MAC",
    venue: "Rynearson Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Ypsilanti",
    state: "MI",
    latitude: 42.2508,
    longitude: -83.6286,
  },
  {
    name: "Kent State Golden Flashes",
    shortName: "Kent State",
    slug: "kent-state",
    abbreviation: "KENT",
    sport: Sport.NCAAF,
    conference2024: "MAC",
    venue: "Dix Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Kent",
    state: "OH",
    latitude: 41.1451,
    longitude: -81.3459,
  },
  {
    name: "Miami (OH) RedHawks",
    shortName: "Miami (OH)",
    slug: "miami-oh",
    abbreviation: "M-OH",
    sport: Sport.NCAAF,
    conference2024: "MAC",
    venue: "Yager Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Oxford",
    state: "OH",
    latitude: 39.5128,
    longitude: -84.7311,
  },
  {
    name: "Northern Illinois Huskies",
    shortName: "Northern Illinois",
    slug: "northern-illinois",
    abbreviation: "NIU",
    sport: Sport.NCAAF,
    conference2024: "MAC",
    venue: "Huskie Stadium",
    venueType: VenueType.OUTDOOR,
    city: "DeKalb",
    state: "IL",
    latitude: 41.9342,
    longitude: -88.7776,
  },
  {
    name: "Ohio Bobcats",
    shortName: "Ohio",
    slug: "ohio",
    abbreviation: "OHIO",
    sport: Sport.NCAAF,
    conference2024: "MAC",
    venue: "Peden Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Athens",
    state: "OH",
    latitude: 39.3214,
    longitude: -82.0966,
  },
  {
    name: "Toledo Rockets",
    shortName: "Toledo",
    slug: "toledo",
    abbreviation: "TOL",
    sport: Sport.NCAAF,
    conference2024: "MAC",
    venue: "Glass Bowl",
    venueType: VenueType.OUTDOOR,
    city: "Toledo",
    state: "OH",
    latitude: 41.6578,
    longitude: -83.6150,
  },
  {
    name: "Western Michigan Broncos",
    shortName: "Western Michigan",
    slug: "western-michigan",
    abbreviation: "WMU",
    sport: Sport.NCAAF,
    conference2024: "MAC",
    venue: "Waldo Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Kalamazoo",
    state: "MI",
    latitude: 42.2826,
    longitude: -85.6044,
  },

  // ─── CONFERENCE USA (10 teams) ────────────────────
  {
    name: "FIU Panthers",
    shortName: "Florida International",
    slug: "florida-international",
    abbreviation: "FIU",
    sport: Sport.NCAAF,
    conference2024: "Conference USA",
    venue: "Pitbull Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Miami",
    state: "FL",
    latitude: 25.7572,
    longitude: -80.3740,
  },
  {
    name: "Jacksonville State Gamecocks",
    shortName: "Jacksonville State",
    slug: "jacksonville-state",
    abbreviation: "JVST",
    sport: Sport.NCAAF,
    conference2024: "Conference USA",
    venue: "Burgess-Snow Field at JSU Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Jacksonville",
    state: "AL",
    latitude: 33.8178,
    longitude: -85.7660,
  },
  {
    name: "Kennesaw State Owls",
    shortName: "Kennesaw State",
    slug: "kennesaw-state",
    abbreviation: "KENN",
    sport: Sport.NCAAF,
    conference2024: "Conference USA",
    venue: "Fifth Third Bank Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Kennesaw",
    state: "GA",
    latitude: 34.0350,
    longitude: -84.5811,
  },
  {
    name: "Liberty Flames",
    shortName: "Liberty",
    slug: "liberty",
    abbreviation: "LIB",
    sport: Sport.NCAAF,
    conference2024: "Conference USA",
    venue: "Williams Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Lynchburg",
    state: "VA",
    latitude: 37.3529,
    longitude: -79.1783,
  },
  {
    name: "Louisiana Tech Bulldogs",
    shortName: "Louisiana Tech",
    slug: "louisiana-tech",
    abbreviation: "LT",
    sport: Sport.NCAAF,
    conference2024: "Conference USA",
    venue: "Joe Aillet Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Ruston",
    state: "LA",
    latitude: 32.5267,
    longitude: -92.6492,
  },
  {
    name: "Middle Tennessee Blue Raiders",
    shortName: "Middle Tennessee State",
    slug: "middle-tennessee-state",
    abbreviation: "MTSU",
    sport: Sport.NCAAF,
    conference2024: "Conference USA",
    venue: "Johnny \"Red\" Floyd Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Murfreesboro",
    state: "TN",
    latitude: 35.8497,
    longitude: -86.3671,
  },
  {
    name: "New Mexico State Aggies",
    shortName: "New Mexico State",
    slug: "new-mexico-state",
    abbreviation: "NMSU",
    sport: Sport.NCAAF,
    conference2024: "Conference USA",
    venue: "Aggie Memorial Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Las Cruces",
    state: "NM",
    latitude: 32.2833,
    longitude: -106.7474,
  },
  {
    name: "Sam Houston Bearkats",
    shortName: "Sam Houston State",
    slug: "sam-houston-state",
    abbreviation: "SHSU",
    sport: Sport.NCAAF,
    conference2024: "Conference USA",
    venue: "Bowers Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Huntsville",
    state: "TX",
    latitude: 30.7147,
    longitude: -95.5441,
  },
  {
    name: "UTEP Miners",
    shortName: "UTEP",
    slug: "texas-el-paso",
    abbreviation: "UTEP",
    sport: Sport.NCAAF,
    conference2024: "Conference USA",
    venue: "Sun Bowl",
    venueType: VenueType.OUTDOOR,
    city: "El Paso",
    state: "TX",
    latitude: 31.7700,
    longitude: -106.5086,
  },
  {
    name: "Western Kentucky Hilltoppers",
    shortName: "Western Kentucky",
    slug: "western-kentucky",
    abbreviation: "WKU",
    sport: Sport.NCAAF,
    conference2024: "Conference USA",
    venue: "Houchens-Smith Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Bowling Green",
    state: "KY",
    latitude: 36.9836,
    longitude: -86.4555,
  },

  // ─── FCS (formerly FBS) ──────────────────────────
  {
    name: "Idaho Vandals",
    shortName: "Idaho",
    slug: "idaho",
    abbreviation: "IDHO",
    sport: Sport.NCAAF,
    conference2024: "FCS",
    venue: "Kibbie Dome",
    venueType: VenueType.DOME,
    city: "Moscow",
    state: "ID",
    latitude: 46.7262,
    longitude: -117.0124,
  },

  // ─── UAB (Sun Belt in 2024 after C-USA) ──────────
  {
    name: "UAB Blazers",
    shortName: "UAB",
    slug: "alabama-birmingham",
    abbreviation: "UAB",
    sport: Sport.NCAAF,
    conference2024: "AAC",
    venue: "Protective Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Birmingham",
    state: "AL",
    latitude: 33.5186,
    longitude: -86.8024,
  },
];
