import { Sport, VenueType } from "@prisma/client";

export interface TeamSeedData {
  name: string;
  abbreviation: string;
  sport: Sport;
  conference: string;
  division: string;
  venue: string;
  venueType: VenueType;
  city: string;
  state: string;
  latitude: number;
  longitude: number;
}

/**
 * All 32 current NFL teams with venue data and coordinates.
 */
export const nflTeams: TeamSeedData[] = [
  // ─── AFC EAST ──────────────────────────────────
  {
    name: "Buffalo Bills",
    abbreviation: "BUF",
    sport: Sport.NFL,
    conference: "AFC",
    division: "East",
    venue: "Highmark Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Orchard Park",
    state: "NY",
    latitude: 42.7738,
    longitude: -78.787,
  },
  {
    name: "Miami Dolphins",
    abbreviation: "MIA",
    sport: Sport.NFL,
    conference: "AFC",
    division: "East",
    venue: "Hard Rock Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Miami Gardens",
    state: "FL",
    latitude: 25.958,
    longitude: -80.2389,
  },
  {
    name: "New England Patriots",
    abbreviation: "NE",
    sport: Sport.NFL,
    conference: "AFC",
    division: "East",
    venue: "Gillette Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Foxborough",
    state: "MA",
    latitude: 42.0909,
    longitude: -71.2643,
  },
  {
    name: "New York Jets",
    abbreviation: "NYJ",
    sport: Sport.NFL,
    conference: "AFC",
    division: "East",
    venue: "MetLife Stadium",
    venueType: VenueType.OUTDOOR,
    city: "East Rutherford",
    state: "NJ",
    latitude: 40.8135,
    longitude: -74.0745,
  },

  // ─── AFC NORTH ─────────────────────────────────
  {
    name: "Baltimore Ravens",
    abbreviation: "BAL",
    sport: Sport.NFL,
    conference: "AFC",
    division: "North",
    venue: "M&T Bank Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Baltimore",
    state: "MD",
    latitude: 39.278,
    longitude: -76.6227,
  },
  {
    name: "Cincinnati Bengals",
    abbreviation: "CIN",
    sport: Sport.NFL,
    conference: "AFC",
    division: "North",
    venue: "Paycor Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Cincinnati",
    state: "OH",
    latitude: 39.0955,
    longitude: -84.516,
  },
  {
    name: "Cleveland Browns",
    abbreviation: "CLE",
    sport: Sport.NFL,
    conference: "AFC",
    division: "North",
    venue: "Huntington Bank Field",
    venueType: VenueType.OUTDOOR,
    city: "Cleveland",
    state: "OH",
    latitude: 41.506,
    longitude: -81.6996,
  },
  {
    name: "Pittsburgh Steelers",
    abbreviation: "PIT",
    sport: Sport.NFL,
    conference: "AFC",
    division: "North",
    venue: "Acrisure Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Pittsburgh",
    state: "PA",
    latitude: 40.4468,
    longitude: -80.0158,
  },

  // ─── AFC SOUTH ─────────────────────────────────
  {
    name: "Houston Texans",
    abbreviation: "HOU",
    sport: Sport.NFL,
    conference: "AFC",
    division: "South",
    venue: "NRG Stadium",
    venueType: VenueType.RETRACTABLE,
    city: "Houston",
    state: "TX",
    latitude: 29.6847,
    longitude: -95.4107,
  },
  {
    name: "Indianapolis Colts",
    abbreviation: "IND",
    sport: Sport.NFL,
    conference: "AFC",
    division: "South",
    venue: "Lucas Oil Stadium",
    venueType: VenueType.RETRACTABLE,
    city: "Indianapolis",
    state: "IN",
    latitude: 39.7601,
    longitude: -86.1639,
  },
  {
    name: "Jacksonville Jaguars",
    abbreviation: "JAX",
    sport: Sport.NFL,
    conference: "AFC",
    division: "South",
    venue: "EverBank Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Jacksonville",
    state: "FL",
    latitude: 30.3239,
    longitude: -81.6373,
  },
  {
    name: "Tennessee Titans",
    abbreviation: "TEN",
    sport: Sport.NFL,
    conference: "AFC",
    division: "South",
    venue: "Nissan Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Nashville",
    state: "TN",
    latitude: 36.1665,
    longitude: -86.7713,
  },

  // ─── AFC WEST ──────────────────────────────────
  {
    name: "Denver Broncos",
    abbreviation: "DEN",
    sport: Sport.NFL,
    conference: "AFC",
    division: "West",
    venue: "Empower Field at Mile High",
    venueType: VenueType.OUTDOOR,
    city: "Denver",
    state: "CO",
    latitude: 39.7439,
    longitude: -105.0201,
  },
  {
    name: "Kansas City Chiefs",
    abbreviation: "KC",
    sport: Sport.NFL,
    conference: "AFC",
    division: "West",
    venue: "GEHA Field at Arrowhead Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Kansas City",
    state: "MO",
    latitude: 39.0489,
    longitude: -94.4839,
  },
  {
    name: "Las Vegas Raiders",
    abbreviation: "LV",
    sport: Sport.NFL,
    conference: "AFC",
    division: "West",
    venue: "Allegiant Stadium",
    venueType: VenueType.DOME,
    city: "Las Vegas",
    state: "NV",
    latitude: 36.0908,
    longitude: -115.1833,
  },
  {
    name: "Los Angeles Chargers",
    abbreviation: "LAC",
    sport: Sport.NFL,
    conference: "AFC",
    division: "West",
    venue: "SoFi Stadium",
    venueType: VenueType.OUTDOOR, // Open-air with a canopy (not a dome)
    city: "Inglewood",
    state: "CA",
    latitude: 33.9535,
    longitude: -118.3392,
  },

  // ─── NFC EAST ──────────────────────────────────
  {
    name: "Dallas Cowboys",
    abbreviation: "DAL",
    sport: Sport.NFL,
    conference: "NFC",
    division: "East",
    venue: "AT&T Stadium",
    venueType: VenueType.RETRACTABLE,
    city: "Arlington",
    state: "TX",
    latitude: 32.7473,
    longitude: -97.0945,
  },
  {
    name: "New York Giants",
    abbreviation: "NYG",
    sport: Sport.NFL,
    conference: "NFC",
    division: "East",
    venue: "MetLife Stadium",
    venueType: VenueType.OUTDOOR,
    city: "East Rutherford",
    state: "NJ",
    latitude: 40.8135,
    longitude: -74.0745,
  },
  {
    name: "Philadelphia Eagles",
    abbreviation: "PHI",
    sport: Sport.NFL,
    conference: "NFC",
    division: "East",
    venue: "Lincoln Financial Field",
    venueType: VenueType.OUTDOOR,
    city: "Philadelphia",
    state: "PA",
    latitude: 39.9008,
    longitude: -75.1675,
  },
  {
    name: "Washington Commanders",
    abbreviation: "WAS",
    sport: Sport.NFL,
    conference: "NFC",
    division: "East",
    venue: "Northwest Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Landover",
    state: "MD",
    latitude: 38.9076,
    longitude: -76.8645,
  },

  // ─── NFC NORTH ─────────────────────────────────
  {
    name: "Chicago Bears",
    abbreviation: "CHI",
    sport: Sport.NFL,
    conference: "NFC",
    division: "North",
    venue: "Soldier Field",
    venueType: VenueType.OUTDOOR,
    city: "Chicago",
    state: "IL",
    latitude: 41.8623,
    longitude: -87.6167,
  },
  {
    name: "Detroit Lions",
    abbreviation: "DET",
    sport: Sport.NFL,
    conference: "NFC",
    division: "North",
    venue: "Ford Field",
    venueType: VenueType.DOME,
    city: "Detroit",
    state: "MI",
    latitude: 42.34,
    longitude: -83.0456,
  },
  {
    name: "Green Bay Packers",
    abbreviation: "GB",
    sport: Sport.NFL,
    conference: "NFC",
    division: "North",
    venue: "Lambeau Field",
    venueType: VenueType.OUTDOOR,
    city: "Green Bay",
    state: "WI",
    latitude: 44.5013,
    longitude: -88.0622,
  },
  {
    name: "Minnesota Vikings",
    abbreviation: "MIN",
    sport: Sport.NFL,
    conference: "NFC",
    division: "North",
    venue: "U.S. Bank Stadium",
    venueType: VenueType.DOME,
    city: "Minneapolis",
    state: "MN",
    latitude: 44.9736,
    longitude: -93.2575,
  },

  // ─── NFC SOUTH ─────────────────────────────────
  {
    name: "Atlanta Falcons",
    abbreviation: "ATL",
    sport: Sport.NFL,
    conference: "NFC",
    division: "South",
    venue: "Mercedes-Benz Stadium",
    venueType: VenueType.RETRACTABLE,
    city: "Atlanta",
    state: "GA",
    latitude: 33.7554,
    longitude: -84.401,
  },
  {
    name: "Carolina Panthers",
    abbreviation: "CAR",
    sport: Sport.NFL,
    conference: "NFC",
    division: "South",
    venue: "Bank of America Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Charlotte",
    state: "NC",
    latitude: 35.2258,
    longitude: -80.8528,
  },
  {
    name: "New Orleans Saints",
    abbreviation: "NO",
    sport: Sport.NFL,
    conference: "NFC",
    division: "South",
    venue: "Caesars Superdome",
    venueType: VenueType.DOME,
    city: "New Orleans",
    state: "LA",
    latitude: 29.9511,
    longitude: -90.0812,
  },
  {
    name: "Tampa Bay Buccaneers",
    abbreviation: "TB",
    sport: Sport.NFL,
    conference: "NFC",
    division: "South",
    venue: "Raymond James Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Tampa",
    state: "FL",
    latitude: 27.9759,
    longitude: -82.5033,
  },

  // ─── NFC WEST ──────────────────────────────────
  {
    name: "Arizona Cardinals",
    abbreviation: "ARI",
    sport: Sport.NFL,
    conference: "NFC",
    division: "West",
    venue: "State Farm Stadium",
    venueType: VenueType.RETRACTABLE,
    city: "Glendale",
    state: "AZ",
    latitude: 33.5276,
    longitude: -112.2626,
  },
  {
    name: "Los Angeles Rams",
    abbreviation: "LAR",
    sport: Sport.NFL,
    conference: "NFC",
    division: "West",
    venue: "SoFi Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Inglewood",
    state: "CA",
    latitude: 33.9535,
    longitude: -118.3392,
  },
  {
    name: "San Francisco 49ers",
    abbreviation: "SF",
    sport: Sport.NFL,
    conference: "NFC",
    division: "West",
    venue: "Levi's Stadium",
    venueType: VenueType.OUTDOOR,
    city: "Santa Clara",
    state: "CA",
    latitude: 37.4033,
    longitude: -121.9694,
  },
  {
    name: "Seattle Seahawks",
    abbreviation: "SEA",
    sport: Sport.NFL,
    conference: "NFC",
    division: "West",
    venue: "Lumen Field",
    venueType: VenueType.OUTDOOR,
    city: "Seattle",
    state: "WA",
    latitude: 47.5952,
    longitude: -122.3316,
  },
];
