import { Pick, DayRecord, SportRecord } from "./types";

export const mockPicks: Pick[] = [
  {
    id: "1",
    sport: "NCAAMB",
    homeTeam: { name: "Michigan", abbreviation: "MICH", color: "#00274C" },
    awayTeam: { name: "Ohio State", abbreviation: "OSU", color: "#BB0000" },
    gameTime: "7:00 PM ET",
    pick: "Michigan -3.5",
    confidence: 5,
    reasoning: "Defense dominates: Michigan's adj. defense ranks #1 nationally",
    socialProof: 87,
    tracked: false,
    inParlay: false,
    signals: [
      { label: "Defensive Rating", value: 95, color: "#00274C" },
      { label: "Line Movement", value: 78, color: "#10B981" },
      { label: "Recent Form", value: 82, color: "#F59E0B" },
    ],
  },
  {
    id: "2",
    sport: "NBA",
    homeTeam: { name: "Celtics", abbreviation: "BOS", color: "#007A33" },
    awayTeam: { name: "Lakers", abbreviation: "LAL", color: "#552583" },
    gameTime: "8:30 PM ET",
    pick: "UNDER 224.5",
    confidence: 5,
    reasoning: "Both teams bottom-5 in pace last 10 games, total inflated by name value",
    socialProof: 73,
    tracked: false,
    inParlay: false,
    signals: [
      { label: "Pace Analysis", value: 90, color: "#007A33" },
      { label: "Total Trend", value: 85, color: "#10B981" },
      { label: "Public Fade", value: 72, color: "#F59E0B" },
    ],
  },
  {
    id: "3",
    sport: "NFL",
    homeTeam: { name: "Chiefs", abbreviation: "KC", color: "#E31837" },
    awayTeam: { name: "Bills", abbreviation: "BUF", color: "#00338D" },
    gameTime: "4:25 PM ET",
    pick: "Bills +2.5",
    confidence: 5,
    reasoning: "Bills 8-2 ATS as road dogs, KC defense allowing 6+ YPA last 3 weeks",
    socialProof: 64,
    tracked: false,
    inParlay: false,
    signals: [
      { label: "ATS Trend", value: 88, color: "#00338D" },
      { label: "Defensive Decline", value: 76, color: "#EF4444" },
      { label: "QB Matchup", value: 80, color: "#10B981" },
    ],
  },
  {
    id: "4",
    sport: "NCAAMB",
    homeTeam: { name: "Duke", abbreviation: "DUKE", color: "#003087" },
    awayTeam: { name: "UNC", abbreviation: "UNC", color: "#7BAFD4" },
    gameTime: "9:00 PM ET",
    pick: "OVER 152.5",
    confidence: 4,
    reasoning: "Rivalry game + both teams top-20 in adj. tempo, last 5 meetings avg 161 pts",
    socialProof: 71,
    tracked: false,
    inParlay: false,
    signals: [
      { label: "Tempo Rating", value: 84, color: "#003087" },
      { label: "Rivalry Factor", value: 70, color: "#F59E0B" },
      { label: "Scoring Trend", value: 78, color: "#10B981" },
    ],
  },
  {
    id: "5",
    sport: "NBA",
    homeTeam: { name: "Nuggets", abbreviation: "DEN", color: "#0E2240" },
    awayTeam: { name: "Thunder", abbreviation: "OKC", color: "#007AC1" },
    gameTime: "9:00 PM ET",
    pick: "Nuggets -4.5",
    confidence: 4,
    reasoning: "Jokić averaging triple-double at home, OKC 2-6 ATS in altitude games",
    socialProof: 68,
    tracked: false,
    inParlay: false,
    signals: [
      { label: "Home Court", value: 82, color: "#0E2240" },
      { label: "Star Power", value: 88, color: "#F59E0B" },
      { label: "Altitude Edge", value: 74, color: "#10B981" },
    ],
  },
  {
    id: "6",
    sport: "NCAAF",
    homeTeam: { name: "Alabama", abbreviation: "ALA", color: "#9E1B32" },
    awayTeam: { name: "Georgia", abbreviation: "UGA", color: "#BA0C2F" },
    gameTime: "3:30 PM ET",
    pick: "UNDER 44.5",
    confidence: 3,
    reasoning: "Top-10 defenses meet, weather calling for 15mph winds",
    socialProof: 58,
    tracked: false,
    inParlay: false,
    signals: [
      { label: "Defensive Match", value: 80, color: "#9E1B32" },
      { label: "Weather Impact", value: 65, color: "#6B7280" },
      { label: "Under Trend", value: 70, color: "#10B981" },
    ],
  },
  {
    id: "7",
    sport: "NFL",
    homeTeam: { name: "Ravens", abbreviation: "BAL", color: "#241773" },
    awayTeam: { name: "Bengals", abbreviation: "CIN", color: "#FB4F14" },
    gameTime: "1:00 PM ET",
    pick: "Ravens -6.5",
    confidence: 3,
    reasoning: "Lamar 14-3 at home vs division, Bengals missing 2 OL starters",
    socialProof: 61,
    tracked: false,
    inParlay: false,
    signals: [
      { label: "Division Record", value: 76, color: "#241773" },
      { label: "Injury Edge", value: 68, color: "#EF4444" },
      { label: "Rushing Attack", value: 72, color: "#10B981" },
    ],
  },
  {
    id: "8",
    sport: "NBA",
    homeTeam: { name: "Warriors", abbreviation: "GSW", color: "#1D428A" },
    awayTeam: { name: "Suns", abbreviation: "PHX", color: "#1D1160" },
    gameTime: "10:00 PM ET",
    pick: "Suns +6",
    confidence: 2,
    reasoning: "Suns 7-3 ATS as road dogs this season, Booker back from rest",
    socialProof: 52,
    tracked: false,
    inParlay: false,
    signals: [
      { label: "ATS Record", value: 65, color: "#1D1160" },
      { label: "Rest Advantage", value: 60, color: "#F59E0B" },
      { label: "Value Spot", value: 58, color: "#10B981" },
    ],
  },
];

export const mockDayRecords: DayRecord[] = [
  { date: "Mon", wins: 4, losses: 2 },
  { date: "Tue", wins: 3, losses: 3 },
  { date: "Wed", wins: 5, losses: 1 },
  { date: "Thu", wins: 2, losses: 3 },
  { date: "Fri", wins: 4, losses: 2 },
  { date: "Sat", wins: 6, losses: 2 },
  { date: "Sun", wins: 3, losses: 1 },
];

export const mockSportRecords: SportRecord[] = [
  { sport: "NFL", wins: 42, losses: 28, pushes: 3 },
  { sport: "NBA", wins: 56, losses: 38, pushes: 2 },
  { sport: "NCAAMB", wins: 78, losses: 44, pushes: 5 },
  { sport: "NCAAF", wins: 35, losses: 22, pushes: 1 },
];

export const recentResults: (Pick & { result: "win" | "loss" | "push" })[] = [
  { ...mockPicks[0], id: "r1", pick: "Michigan -3.5", result: "win", confidence: 5, tracked: true, inParlay: false },
  { ...mockPicks[1], id: "r2", pick: "UNDER 221", result: "win", confidence: 4, tracked: true, inParlay: false },
  { ...mockPicks[2], id: "r3", pick: "Bills +3", result: "loss", confidence: 3, tracked: true, inParlay: false },
  { ...mockPicks[3], id: "r4", pick: "OVER 148.5", result: "win", confidence: 5, tracked: true, inParlay: false },
  { ...mockPicks[4], id: "r5", pick: "Nuggets -5", result: "win", confidence: 4, tracked: true, inParlay: false },
  { ...mockPicks[5], id: "r6", pick: "UNDER 42", result: "loss", confidence: 3, tracked: false, inParlay: false },
  { ...mockPicks[6], id: "r7", pick: "Ravens -7", result: "push", confidence: 3, tracked: true, inParlay: false },
  { ...mockPicks[7], id: "r8", pick: "Suns +5.5", result: "win", confidence: 2, tracked: false, inParlay: false },
];
